### ISSUE TITLE
Switch parser to be based on stream of RDF triples

### ISSUE THREAD

**Issue by hobofan** [field33/owlish#2]
As of version `0.2.0` of `harriet`, it is possible to convert a parsed Turtle document to a stream of RDF triples.

Parsing on that stream of RDF triples instead of the AST provided by `harriet`, should allow a much more robust parser that can handle all the different AST constructs that yield the same triples.

One of the OWL2 specification document (https://www.w3.org/TR/2012/REC-owl2-mapping-to-rdf-20121211/) describes how to parse an ontology from RDF triples. Specifically section 3 specifies the mapping for the direction RDF->OWL (https://www.w3.org/TR/2012/REC-owl2-mapping-to-rdf-20121211/#Mapping_from_RDF_Graphs_to_the_Structural_Specification).

**Comment by floers** [comment]
resolved with https://github.com/field33/owlish/pull/13
